# Generated by Django 2.2.15 on 2021-01-03 07:41

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('api', '0003_auto_20210103_0736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageQuestion',
            new_name='ImageLesionQuestion',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='LesionQuestion',
        ),
    ]
