# Generated by Django 2.2.15 on 2021-01-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210103_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesionquestion',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
