# Generated by Django 2.2.3 on 2021-01-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210104_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
