# Generated by Django 2.2.3 on 2021-01-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bodyparts_userbodyparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='next_reminder',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='reminder_frequency',
            field=models.IntegerField(default=0),
        ),
    ]
