# Generated by Django 2.2.3 on 2021-01-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210119_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesionquestion',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
