# Generated by Django 2.2.3 on 2021-05-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_lesionquestion_has_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
